import type { Metadata } from "next";

import { inter } from "@/components/fonts";
import Hosts from "@/components/Hosts";
import Providers from "@/components/Providers";
import Tools from "@/components/Tools";
import { cn } from "@/utils/tailwindcss/mergeClassNames";
import React from "react";

import "./globals.css";

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: {
    apple: [
      { sizes: "180x180", type: "image/png", url: "/apple-touch-icon.png" },
    ],
    icon: [
      { sizes: "32x32", type: "image/png", url: "/favicon-32x32.png" },
      { sizes: "16x16", type: "image/png", url: "/favicon-16x16.png" },
    ],
  },
  manifest: "/manifest.json",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.variable, "antialiased transform-gpu")}>
        <Providers>
          {children}
          <Hosts />
          <Tools />
        </Providers>
      </body>
    </html>
  );
}
